version: '3'
services:
  sql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "127.0.0.1:3306:3306"

    volumes:
      - "./data:/var/lib/mysql"
      - "./sql:/sql"
      - "./additional.cnf:/etc/mysql/mysql.conf.d/additional.cnf"
